### ISSUE TITLE
0.9.1在php7.0下会运行错误

### ISSUE THREAD

**Issue by wen10603654852** [metowolf/BilibiliHelper#39]
更换7.2恢复
日志如下
[2018-05-09 18:28:09] Bilibili.NOTICE: 连接弹幕服务器
PHP Fatal error:  Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php:417
Stack trace:
#0 /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Client.php(244): Wrench\Protocol\Protocol->validateResponseHandshake('H', '8A2esWlGpC8oIfz...')
#1 /*/BilibiliHelper/src/plugins/Danmaku.php(109): Wrench\Client->connect()
#2 /*/BilibiliHelper/src/plugins/Danmaku.php(133): BilibiliHelper\Plugin\Danmaku::connect()
#3 /*/BilibiliHelper/src/plugins/Danmaku.php(48): BilibiliHelper\Plugin\Danmaku::heart()
#4 /*/BilibiliHelper/src/plugins/Base.php(36): BilibiliHelper\Plugin\Danmaku::work()
#5 /*/BilibiliHelper/index.php(36): BilibiliHelper\Plugin\Base::run(Array)
#6 {main}
  thrown in /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php on line 417

Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php:417
Stack trace:
#0 /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Client.php(244): Wrench\Protocol\Protocol->validateResponseHandshake('H', '8A2esWlGpC8oIfz...')
#1 /*/BilibiliHelper/src/plugins/Danmaku.php(109): Wrench\Client->connect()
#2 /*/BilibiliHelper/src/plugins/Danmaku.php(133): BilibiliHelper\Plugin\Danmaku::connect()
#3 /*/BilibiliHelper/src/plugins/Danmaku.php(48): BilibiliHelper\Plugin\Danmaku::heart()
#4 /*/BilibiliHelper/src/plugins/Base.php(36): BilibiliHelper\Plugin\Danmaku::work()
#5 /*/BilibiliHelper/index.php(36): BilibiliHelper\Plugin\Base::run(Array)
#6 {main}
  thrown in /*/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php on line 417

**Comment by NeverBehave** [comment]
@wen10603654852 这个不就是我们之前遇到的那个……
把 wss 换成 ws，2245 改成 2244

**Comment by wtlusvm** [comment]
我这也有相同的问题（

**Comment by oneyian** [comment]
/BilibiliHelper/src/plugins/Danmaku.php  
把 wss 换成 ws，2245 改成 2244

我这里这样解决
