### ISSUE TITLE
 连接弹幕服务器抛出异常

### ISSUE THREAD

**Issue by ZeusGamingPlay** [metowolf/BilibiliHelper#42]
PHP Fatal error:  Uncaught exception 'Wrench\Exception\HandshakeException' with message 'No accept header receieved on handshake response' in /home/ownAccount/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php:417
Stack trace:
#0 /home/ownAccount/vendor/wrench/wrench/lib/Wrench/Client.php(244): Wrench\Protocol\Protocol->validateResponseHandshake('H', 'm9P68WWe1Xyjx5s...')
#1 /home/ownAccount/src/plugins/Danmaku.php(109): Wrench\Client->connect()
#2 /home/ownAccount/src/plugins/Danmaku.php(133): BilibiliHelper\Plugin\Danmaku::connect()
#3 /home/ownAccount/src/plugins/Danmaku.php(48): BilibiliHelper\Plugin\Danmaku::heart()
#4 /home/ownAccount/src/plugins/Base.php(36): BilibiliHelper\Plugin\Danmaku::work()
#5 /home/ownAccount/index.php(36): BilibiliHelper\Plugin\Base::run(Array)
#6 {main}
  thrown in /home/ownAccount/vendor/wrench/wrench/lib/Wrench/Protocol/Protocol.php on line 417

PHP环境5.6.1 Centos 6.4 x64

**Comment by ZeusGamingPlay** [comment]
看了之前的issue自行解决了问题，打扰咯～
