### ISSUE TITLE
Ubuntu 16.04使用Node.js构建报错：SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by Lei-Houjyu** [metowolf/BilibiliHelper#96]
```
$ node -v
v4.2.6
$ node index.js
/home/howie/BilibiliHelper/index.js:23
const app = async () => {
                  ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by LoliLin** [comment]
请 8.x 或以上版本的 Node.js 启动项目
